name: Build and Deploy

on:
  push:
    branches: [ main ]
    tags: [ 't*', 'p*' ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    uses: aloma-io/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: 'aloma-io'
      dockerfile: 'Dockerfile'
      context: '.'
      tags: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
    secrets:
      AZURE_USER: ${{ secrets.REGISTRY_USER }}
      AZURE_PASS: ${{ secrets.REGISTRY_PASS }}
      GOOGLE_CLOUD_KEY: ${{ secrets.GOOGLE_CLOUD_KEY }}
